[package]
name = "pomodoro_timer"
version = "0.1.0"
edition = "2021"

[dependencies]
slint = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
notify-rust = "4.11"
rodio = "0.17"
rfd = "0.14"

[build-dependencies]
slint-build = "1.3"